- src/bin/nix-locate.rs
Otherwise `nix-locate` can't find the db. Looks like an oversight after https://github.com/bennofs/nix-index/commit/df38f0fa1621e7b9274a61f9004ac960bbabf4cc.
> Fix path to database in nix-locate

- command-not-found.sh
This adds in the autorun/autoinstall handling for the bash scripts.
I've also fixed a change to the multiple args handling that broke ZSH scripts. The new fix should work in both Bash and ZSH.
Some other formatting changes as well.
> Add NIX_AUTO_RUN/NIX_AUTO_INSTALL handling

- src/bin/nix-index.rs
Here are some small refactoring proposals that build up to a clean way to treat Hydra request errors as indicating that a store path does not have a file list available. The final patch fixes #25 and makes `nix-index` usable given the current state of `cache.nixos.org`.
> Ignore fetch failures

- command-not-found.sh
this makes it possible to use set -u in your shell while also sourcing this script.
> Allow set -u in command-not-found.sh

- src/bin/nix-index.rs
- src/database.rs
- src/files.rs
Added a way to only put paths starting with a certain prefix into the database, through a `--filter-prefix` flag. Should resolve #176, and is a way to solve NixOS/nixpkgs#39789.
```
--filter-prefix <PREFIX>    Only add paths starting with PREFIX (e.g. `/bin/`)
```
Some typos were also fixed.
> feat: added prefix filtering support

- default.nix
altogether, these changes allow you to do things like `final.callPackage sources.nix-index { };` in a Nix Flake.
I disabled checks here since they appear to be system-dependent (they pass on Linux, but not on Darwin.) The same logic is applied in nixpkgs.
> add some fixes for Darwin and Flakes

- src/bin/nix-index.rs
Fixes https://github.com/bennofs/nix-index/issues/178.
Thanks @hqurve for finding exactly where this needed to be changed :)
> nix-index: xlibs has become xorg in recent Nixpkgs

- flake.nix
Building for aarch64-linux seems to just work.  But to expose the package in the flake it is necessary to add the aarch64-linux build target to the flake.nix
> add aarch64-linux build target for flakes

- Cargo.lock
- Cargo.toml
- src/bin/nix-index.rs
- src/bin/nix-locate.rs
- src/files.rs
This PR updates clap to version 3, and uses clap's new `#[derive(Parser)]` feature to rely on clap more heavily for parsing args.
Also bump to the 2021 edition, to enable disjoint capture in closures.
> Move from clap-v2 to clap-v3

- Cargo.toml
- src/bin/nix-index.rs
- src/bin/nix-locate.rs
This allows setting the database location also via `NIX_INDEX_DATABASE`, since overriding `XDG_CACHE_HOME` might have unwanted side effects (cf. Mic92/nix-index-database#48). Fixes #143 and nix-community/comma#50.
> feat: Set database location from NIX_INDEX_DATABASE

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- src/bin/nix-locate.rs
related: #200
before
```
Crate:     h2
Version:   0.3.15
Title:     Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)
Date:      2023-04-14
ID:        RUSTSEC-2023-0034
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0034
Solution:  Upgrade to >=0.3.17
Dependency tree:
h2 0.3.15
└── hyper 0.14.23
├── nix-index 0.1.7
├── hyper-tls 0.5.0
│   └── hyper-proxy 0.9.1
│       └── nix-index 0.1.7
└── hyper-proxy 0.9.1
Crate:     openssl
Version:   0.10.45
Title:     `openssl` `SubjectAlternativeName` and `ExtendedKeyUsage::other` allow arbitrary file read
Date:      2023-03-24
ID:        RUSTSEC-2023-0023
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0023
Solution:  Upgrade to >=0.10.48
Dependency tree:
openssl 0.10.45
└── native-tls 0.2.11
├── …
```
> get rid of all but 1 vulnerability

- command-not-found.sh
> fix(command-not-found): nix command suggestions

- src/nixpkgs.rs
before
```
caused by: nix-env failed with error: nix-env failed with unknown exit code:
```
after
```
caused by: nix-env failed with error: nix-env failed with signal: 9 (SIGKILL):
```
this will make issues like #157 more diagnosable
> feat(nix-index): improve error message when `nix-env` is killed by signal

- flake.nix
This makes nix flake check and buildbot-nix work out of box
> build all packages/devShells in checks

- src/lib.rs
Otherwise we hit the newly added redirect and fail.
> fix: use HTTPS for cache.nixos.org

- Cargo.lock
- Cargo.toml
- flake.lock
- src/bin/nix-index.rs
- src/hydra.rs
- src/listings.rs
Things we get for free now:
- HTTPS
- content decoding
- timeouts
- more?
Also some drive-by dependency updates, also rewrite some code from future combinators to more modern async-await style.
> feat: rewrite client to use reqwest

- src/listings.rs
This makes it possible to search for texlive packages using nix-index.
Fixes #253
> Add texlive.pkgs to EXTRA_SCOPES

- src/database.rs
Noticed that nix-index-database "small" mostly consists of package(^p\0) lines without its corresponding path as many nix packages don't have entries under /bin/.
This reduced the small index size from 3.9MB to 967K. Whereas the number of paths in the database is identical and equall to 82984(nix-index ran at `github:NixOS/nixpkgs/5aba99242eb2ca90cdc4eea40d61ad9157e5913c`)
> Exclude packages with no files from the index.

- CHANGELOG.md
- command-not-found.sh
- src/bin/nix-locate.rs
It happens pretty often to me that I'm trying to find out which packages contain a certain header file (e.g. `unistd.h`). In those cases I usually don't care at all about which e.g. FHS env has this header as well.
I can't remember a single time where this was actually helpful, so I'm questioning whether this is a sensible default. I'll use this patch in my own setup for now, but I thought I could suggest it here as well.
cc @RaitoBezarius @figsoda @bennofs
> Make `--top-level` the default behavior of `nix-locate`

- command-not-found.nu
Fixes https://github.com/nix-community/nix-index/issues/275
`--top-level` became the default behavior and was removed in https://github.com/nix-community/nix-index/commit/66cd6792464368d9756d0283099bb6918ce8e30a.
> fix(`command-not-found.nu`): don't use `--top-level`
